### ISSUE TITLE
Terminal spams "Could not process image: Skiping frame..."

### ISSUE THREAD

**Issue by Lil2Greasy** [Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter#18] opened 2024-08-22 22:15 UTC
hi so my knowledge of VMs and all this is basically 0.

i followed your guide to the letter and ran into the following issue:

when I try to run the "python3 Switch_Controller.py"-command i get this screen:
![1](https://github.com/user-attachments/assets/41edd9d9-22ee-47e5-bdb7-3b369c8188ff)
when I then select "test switch controller", nothing happens (no pairing request) followed by the following screen:
![2](https://github.com/user-attachments/assets/cd78d995-d007-4f8d-810c-b50b4e00c9e3)
my entire VM then freezes, and I have to force-close the VM and restart it.

bluetooth works (have been able to connect my phone to the VM)

i'll happily provide any extra info you need to solve the issue, and I've also reported the issue to NXBT (waiting for reply there also)

**Comment by Dinones** [comment] 2024-08-22 22:28
Thank you for reporting!

This is the last step of all the [verification steps](https://github.com/Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter/blob/master/Media/Docs/Verify%20Installation.md). It seems the program is not correctly detecting the capture card, and it's not able to read frames from the Nintendo Switch. Can you please confirm:

1. Does the "_[Detecting the Capture Card](https://github.com/Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter/blob/master/Media/Docs/Verify%20Installation.md#--------detecting-the-capture-card)_" step print **_OK_** for any device? 
2. If yes, could you please execute again the `python3 Game_Capture.py` command and select option 2 instead, "Check current capture device"? Does it show the Nintendo Switch screen?

**Comment by Lil2Greasy** [comment] 2024-08-23 13:30
> 1. Does the "_[Detecting the Capture Card](https://github.com/Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter/blob/master/Media/Docs/Verify%20Installation.md#--------detecting-the-capture-card)_" step print **_OK_** for any device? 
yes, it prints "OK" on the same video capture line shown in your screenshot.

> 2. If yes, could you please execute again the `python3 Game_Capture.py` command and select option 2 instead, "_Check current capture device_"? Does it show the Nintendo Switch screen?
yes it shows the switch screen
> 
> > i'll happily provide any extra info you need to solve the issue, and I've also reported the issue to NXBT (waiting for reply there also)
> 
> It has nothing to do with NXBT, as far as we know for now. You can delete that report from their repository, as the issue is with the capture card, not the Bluetooth system.
i assumed it had something to do with NXBT since the issue only occured when I tried the "Controlling the Nintendo Switch" step. 
should I try to run the command again now that i've estabished that the video capture works?

**Comment by Dinones** [comment] 2024-08-23 13:37
Could you please answer both questions so I can understand what is happening exactly?

**Comment by Lil2Greasy** [comment] 2024-08-23 13:44
>1. Does the "[Detecting the Capture Card](https://github.com/Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter/blob/master/Media/Docs/Verify%20Installation.md#--------detecting-the-capture-card)" step print OK for any device?
yes, it prints OK on the first line.

>If yes, could you please execute again the python3 Game_Capture.py command and select option 2 instead, "Check current capture device"? Does it show the Nintendo Switch screen?
yes, when selecting option 2 it shows the Nintendo Switch screen.

the issue only takes place when I try to run the python3 Switch_Controller.py command. 
![image](https://github.com/user-attachments/assets/134ebfe9-3e59-43c1-8fa7-b1e3d594c589)
my system either freezes on this screen, or on the other screen that was attached in my initial issue report.

**Comment by Dinones** [comment] 2024-08-23 14:50
> the issue only takes place when I try to run the python3 Switch_Controller.py command.

So when you run the Game_Capture.py scrips with the second option, the image does show as it should, right?

If yes, could you please open a terminal and run the following command:

```
sudo nxbt demo
```

**Comment by Lil2Greasy** [comment] 2024-08-23 15:47
> > the issue only takes place when I try to run the python3 Switch_Controller.py command.
> 
> So when you run the Game_Capture.py scrips with the second option, the image does show as it should, right?

yes
> 
> If yes, could you please open a terminal and run the following command:
> 
> ```
> sudo nxbt demo
> ```

inside the /module/ folder?

**Comment by Dinones** [comment] 2024-08-24 13:56
Okay, at this point, we can say the problem is related to nxbt. Could you please try reinstalling it:
```
sudo pip install --force-reinstall nxbt
```
You can also try fully restarting your computer (not just the VM). At this point, I understand the Bluetooth card is correctly connected to the VM, right? Does the Bluetooth icon show on the top-right section of the VM?

![image](https://github.com/user-attachments/assets/a5ebc9b7-16ed-417a-9066-52a3c181f7a4)

**Comment by Dinones** [comment] 2024-08-27 08:05
Sure! Now you can try again. I'd start by first running nxbt demo:
```
sudo nxbt demo
```
If it works, you can try with:
```
python3 Switch_Controller.py
```

**Comment by Dinones** [comment] 2024-08-31 12:13
Hi @Lil2Greasy! Could you please confirm if you finally managed to run the program?

**Comment by Dinones** [comment] 2024-09-08 15:55
Closed as @Lil2Greasy not answering.

**Closed by Dinones** 2024-09-08 15:55 UTC
Labels: Installation
